name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          os: [macos-latest, ubuntu-latest]
        fail-fast: false
    runs-on:  ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.18.x'
    - name: Install avachi libraries (mDNS) and asound
      run: sudo apt-get install libavahi-compat-libdnssd-dev libasound2-dev alsa-lib
      if: ${{ matrix.os == 'ubuntu-latest' }}
    - name: Install openssl on macos
      run: |
        brew upgrade openssl@1.1
        brew link --force openssl@1.1
        export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
        pkg-config --modversion openssl
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
      if: ${{ matrix.os == 'macos-latest' }}
    - name: Install python dependencies
      run: python3 -m pip install --upgrade pip setuptools wheel
    - name: Install python3-protobuf
      run: sudo pip3 install protobuf grpcio-tools
    - name: List files in cspot directory
      run: echo "cspot/ files:" && ls cspot && echo "cspot/cJSON files:" && ls cspot/cJSON
    - name: cmake
      run: cd targets/cli && mkdir -p build && cd build && cmake ..
    - name: make
      run: cd  targets/cli/build && make
