name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.3
      with:
        cmake-version: '3.18.x'
    - name: Install python dependencies
      run: python3 -m pip install --upgrade pip setuptools wheel
    - name: Install python3-protobuf
      run: sudo pip3 install protobuf grpcio-tools
    - name: Install cjson
      run: sudo apt-get install -y cjson cjson-dev
    - name: cmake
      run: cd targets/cli && mkdir -p build && cd build && cmake ..
    - name: make
      run: cd  targets/cli/build && make
