name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install python3-protobuf
      run: sudo apt-get install -y python3-protobuf
    - name: cmake
      run: mkdir -p build && cd build && cmake ..
    - name: make
      run: cd build && make
